export { default as APISettings } from "./Api";
export { default as ApplicationSettings } from "./Application";
export { default as DownloadClientSettings } from "./DownloadClient";
export { default as FeedSettings } from "./Feed";
export { default as IndexerSettings } from "./Indexer";
export { default as IrcSettings } from "./Irc";
export { default as LogSettings } from "./Logs";
export { default as NotificationSettings } from "./Notifications";
export { default as ReleaseSettings } from "./Releases";
