version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
      day: saturday
      time: "07:00"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
  - package-ecosystem: pnpm
    directory: /web
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
