version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
       github-dependencies:
          patterns:
            - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
       go-dependencies:
          patterns:
            - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
       npm-dependencies:
          patterns:
            - "*"
