before:
  hooks:
    - go mod tidy

builds:
  - id: autobrr
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/autobrr/main.go
    binary: autobrr
  - id: autobrrctl
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/autobrrctl/main.go
    binary: autobrrctl

archives:
  - id: autobrr
    builds:
      - autobrr
      - autobrrctl
    files:
      - none*
    replacements:
      amd64: x86_64

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - autobrr
      - autobrrctl
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/autobrr/autobrr:{{ .Tag }}"
      - "ghcr.io/autobrr/autobrr:latest"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    goarm: 6
    ids:
      - autobrr
      - autobrrctl
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/autobrr/autobrr:{{ .Tag }}"
      - "ghcr.io/autobrr/autobrr:latest"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    ids:
      - autobrr
      - autobrrctl
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "ghcr.io/autobrr/autobrr:{{ .Tag }}"
      - "ghcr.io/autobrr/autobrr:latest"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/autobrr/autobrr:{{ .Tag }}
    image_templates:
      - ghcr.io/autobrr/autobrr:{{ .Tag }}
      - ghcr.io/autobrr/autobrr:latest

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/autobrr/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## Docker images
    
    - `docker pull ghcr.io/autobrr/autobrr:{{ .Tag }}`
    
    ## What to do next?
    
    - Read the [documentation](https://autobrr.com)
    - Join our [Discord server](https://discord.gg/WQ2eUycxyT)

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
