before:
  hooks:
    - go mod tidy

builds:
  - id: autobrr
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/autobrr/main.go
    binary: autobrr
  - id: autobrrctl
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/autobrrctl/main.go
    binary: autobrrctl

archives:
  - id: autobrr
    builds:
      - autobrr
      - autobrrctl
    files:
      - none*
    replacements:
      amd64: x86_64

release:
  prerelease: auto

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
