---
version: "2.1"
services:
  autobrr:
    image: autobrr:dev
    container_name: autobrr
    volumes:
      - ./config:/config
    ports:
      - "7474:7474"
    restart: unless-stopped
  postgres:
    image: postgres:12.10
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=autobrr
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autobrr
  test_postgres:
    image: postgres:12.10
    container_name: autobrr_postgres_test
    volumes:
      - test_postgres:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=autobrr


volumes:
  postgres:
  test_postgres:
