name: Golang linters
on:
  push:
    branches:
      - "master"
      - "develop"
    tags:
      - 'v*'
  pull_request:

jobs:
  nilaway:
    name: Nilaway Linter
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true

      - name: Install Nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest

      - name: Nilaway
        run: nilaway ./...
