name: Trigger Docs Update

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  trigger_docs_update:
    runs-on: ubuntu-latest
    # only run if the 'build' workflow was successful and was triggered by a tag push
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
    steps:
      - name: Trigger docs workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DOCS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/autobrr/autobrr.com/dispatches \
            -d '{"event_type": "update-release-notes"}'
